services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    networks:
      mycomposenetwork:
        ipv4_address: 172.20.0.4
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - mycomposenetwork

networks:
  mycomposenetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"
          gateway: "172.20.0.1"
